version: '3.3'
services:
  prud-core:
    image: nighmared/prud
    build:
      context: ./
      dockerfile: ./core/Dockerfile
    restart: on-failure
    environment:
      - PRUD_WEBHOOK_URL=${WEBHOOK_URL}
      - PRUD_OLDEST_POST_TO_SEND_TS=1689353832
    volumes:
      - prud_data:/data
  prud-api:
    image: nighmared/prud-api
    ports:
      - 8801:80
    build:
      context: ./
      dockerfile: ./web/api/Dockerfile
    restart: on-failure
    volumes:
      - prud_data:/data
  prud-web:
    image: nighmared/prud-web
    build:
      context: ./web/prud-web/
      dockerfile: Dockerfile
    ports:
      - 8802:3000
    environment:
      - WEB_API_HOST=${WEB_API_HOST:-polyring-updater_prud-api_1}
      - WEB_API_PORT=${WEB_API_PORT:-80}

volumes:
  prud_data:
