version: "3.3"
services:
  prud-core:
    image: nighmared/prud-core
    restart: unless-stopped
    environment:
      - PRUD_WEBHOOK_URL=${WEBHOOK_URL}
      - PRUD_OLDEST_POST_TO_SEND_TS=1689353832
    volumes:
      - prud_data:/data
  prud-api:
    image: nighmared/prud-api
    ports:
      - 8801:80
    restart: unless-stopped
    volumes:
      - prud_data:/data
  prud-web:
    restart: unless-stopped
    image: nighmared/prud-web
    ports:
      - 8802:3000

volumes:
  prud_data:
