version: '3.3'
services:
  prud-core:
    image: nighmared/prud
    build:
      context: ./
      dockerfile: ./core/Dockerfile
    restart: on-failure
    environment:
      - PRUD_WEBHOOK_URL=${WEBHOOK_URL}
      - PRUD_OLDEST_POST_TO_SEND_TS=1686296861
    volumes:
      - prud_data:/data
  prud-api:
    image: nighmared/prud-api
    build:
      context: ./
      dockerfile: ./web/api/Dockerfile
    restart: on-failure
    volumes:
      - prud_data:/data

volumes:
  prud_data:
