"""pls make this work

Revision ID: 0a42ec9b08ea
Revises: ab089d123542
Create Date: 2025-03-16 18:39:33.642436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a42ec9b08ea'
down_revision: Union[str, None] = 'ab089d123542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polyringfeed', 'last_disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polyringfeed', sa.Column('last_disabled', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
