"""updated field

Revision ID: da3dc6950230
Revises: e1b8c23747ac
Create Date: 2024-02-01 22:33:06.381160

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da3dc6950230"
down_revision: Union[str, None] = "e1b8c23747ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "polyringfeed", sa.Column("disabled_until", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "polyringfeed", sa.Column("backoff_level", sa.Integer(), nullable=True)
    )
    op.drop_column("polyringfeed", "disable_count")  

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "polyringfeed", sa.Column("last_disabled", sa.INTEGER(), nullable=True)
    )
    op.drop_column("polyringfeed", "disabled_until")
    op.add_column(
        "polyringfeed", sa.Column("disable_count", sa.INTEGER(), nullable=True)
    )
    op.drop_column("polyringfeed", "backoff_level")
    # ### end Alembic commands ###
