"""add additional fields to feeds

Revision ID: e1b8c23747ac
Revises: 2e98d950adfa
Create Date: 2024-02-01 21:02:18.360329

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1b8c23747ac"
down_revision: Union[str, None] = "2e98d950adfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "polyringfeed", sa.Column("disable_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "polyringfeed", sa.Column("last_disabled", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("polyringfeed", "last_disabled")
    op.drop_column("polyringfeed", "disable_count")
    # ### end Alembic commands ###
